//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrueba2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int id { get; set; }
        public string RFCProspecto { get; set; }
        public string nombre { get; set; }
        public string realname { get; set; }
        public byte[] documento { get; set; }
    }
}
